### ISSUE TITLE
BCNet with male or female SMPL model

### ISSUE THREAD

**Issue by Luciano07** [jby1993/BCNet#8]
Hi,

Is possible to use BCNet with male or female SMPL models, instead neutral model? What format should be used?
Why do you use a '*.txt' file instead of a *.pkl file to import SMPL model?
Any explanation will be helpful for me.

Thank for the great work!

**Comment by jby1993** [comment]
BCNet is trained based on the neutral model, therefore it's not suitable for gender-specific model due to some different SMPL parameters. '*.txt' is a code legacy issue. If you want to use gender-specific models with my SMPL code, you can download [here](https://mailustceducn-my.sharepoint.com/:f:/g/personal/jby1993_mail_ustc_edu_cn/EqosuuD2slZCuZeVI2h4RiABM5AWBZeM0yhVSuMrcoTIbA?e=mOROuA), all the '*.pkl' files are converted from official codes by myself and should work for my code now.

**Comment by Luciano07** [comment]
Thanks for the quick answer! male and female models works well with your code.
I have another question, Is possible to obtain pose parameters (thetas) in 72 parameter values array format from BCNet?

**Comment by jby1993** [comment]
You need to transform the matrix rotation representation to the axis-angle representation.

**Comment by Luciano07** [comment]
Thanks for the explanation! clear for me.

**Comment by lll-gen** [comment]
I have a question as to why I use female and male PKL respectively and get the same result.
